### ISSUE TITLE
New fabric mods not included

### ISSUE THREAD

**Issue by TheMegax** [John-Paul-R/fibermc#18]
All new fabric mods aren't being included in the list, despite the list update time saying otherwise. Searching by date on curseforge, it seems that all mods after June 19 2021 are excluded. Additionally, the Fabric Category is nowhere to be seen. Did they remove fabric from the API?

**Comment by John-Paul-R** [comment]
CurseForge recently removed the fabric category. Additionally, I am in the process of rewriting my site's backend entirely, as my old method of updating no longer works.

It will be unable to add new mods until I am done with this rewrite.

**Comment by NebelNidas** [comment]
Can you give us a rough estimate of how long the rewrite will take?

**Comment by John-Paul-R** [comment]
@NebelNidas Entirely reasonable question. Unfortunately, the best answer I've got is "however long it takes for my motivation and free time to align for long enough to do it".

Which I understand is aggravatingly nonspecific, but that's just where I'm at atm.

**Comment by John-Paul-R** [comment]
Should be resolved as of now. Just released what I'm calling "fibermc v2". The list now once again updates regularly and has [Modrinth](https://modrinth.com) integration!

Live at https://www.fibermc.com.
Full changelog here: https://github.com/John-Paul-R/fibermc/releases/tag/v2.0
