### ISSUE TITLE
[UI] - author names can get stacked... somehow, when scrolling.

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/fibermc#22]
[UI] - author names can get stacked... somehow, when scrolling.
![chrome_RBMfTaS25M](https://user-images.githubusercontent.com/29154459/150647118-3425d171-9e18-4b1a-81df-6606ce154679.png)

Can't reproduce atm, but it happened once. If anyone knows how to make this happen again, I'd appreciate the info.

**Comment by Techie-Pi** [comment]
![image](https://user-images.githubusercontent.com/48295028/151693308-e07aafad-0e67-4d5e-8f2f-5ca3ddd8c14c.png)
Happens everytime I scroll through the page, after ~20 mods.

Chrome 97.0. I'll try to debug, to find why it happens

**Comment by John-Paul-R** [comment]
Looked into this a bit more after seeing your comment. Here are some additional things I discovered:

  - This only happens on the compact list view, not the detailed list view.
  - If you swap to the detailed list view, then go back to the compact list view, the issue will be gone until you refresh the page.

This bug is super weird, largely due to the fact that my list batching system is... more than slightly cursed.
