### ISSUE TITLE
"Latest Supported Version" doesn't use canonical version ordering

### ISSUE THREAD

**Issue by sleepingdragoninn** [John-Paul-R/fibermc#27]
1.18-pre7 is listed above 1.18.2, etc.

**Comment by John-Paul-R** [comment]
Thanks for reporting this. Should be fixed for "pre" and "rc" versions on the live site now. Snapshot versions like `22w14a` will still appear 1st though. Might address this in the future, but that is a more complex fix.

Lmk if anything still seems out-of-whack.
